### ISSUE TITLE
Can't npm install express-thumbnail

### ISSUE THREAD

**Issue by datdinhquoc** [Vaidas737/express-thumbnail#6]
I'm on centos 7, node stable (10.10.0)

When installing express-thumbnail, there's an error compiling lwip:

```
In file included from ../src/lib/png/png.c:14:0:
../src/lib/png/pngpriv.h:805:4: error: #error ZLIB_VERNUM != PNG_ZLIB_VERNUM "-I (include path) error: see the notes in pngpriv.h"
 #  error ZLIB_VERNUM != PNG_ZLIB_VERNUM \
    ^
make: *** [Release/obj.target/lwip_decoder/src/lib/png/png.o] Error 1
```

It seems installing fine with nodejs 6 and before, but not from nodejs 7.

**Comment by Vaidas737** [comment]
Yes, lwip is out of support.

Maybe is better to switch to imagemagick, but then it will require some extra dependencies.
